module.exports = [
  { label: 'config-ui', path: '/config-ui' },
  { label: 'config-ui - numbers', path: '/config-ui/numbers' },
  { label: 'config-ui - tabs', path: '/config-ui/tabs' },
  { label: 'correct-answer-toggle', path: '/correct-answer-toggle' },
  { label: 'editable-html', path: '/editable-html' },
  { label: 'graphing', path: '/graphing' },
  { label: 'charting', path: '/charting' },
  { label: 'icons', path: '/icons' },
  { label: 'math-evaluator', path: '/math-evaluator' },
  { label: 'math-input', path: '/math-input' },
  { label: 'render-ui', path: '/render-ui' },
  { label: 'scoring-config', path: '/scoring-config' },
  { label: 'text-select', path: '/text-select' },
  { label: 'text-select math', path: '/text-select-math' },
  { label: 'tools - ruler', path: '/tools/ruler' },
  { label: 'tools - protractor', path: '/tools/protractor' },
  { label: 'tools - rotatable', path: '/tools/rotatable' },
  { label: 'drag', path: '/drag' }
];
