#!/usr/bin/env bash

set -e 

cd demo
rm -fr out

./node_modules/.bin/next build
./node_modules/.bin/next export 

export NODE_ENV="production"
cd out
touch .nojekyll
git init
git add .
git commit . -m "static build"
git remote add origin git@github.com:pie-framework/pie-lib.git
git push --force origin master:gh-pages
rm -fr .git

