#!/usr/bin/env node

const argv = require('minimist')(process.argv.slice(2));
const { execSync } = require('child_process');

const cmd = `./node_modules/.bin/jest ${
  argv.scope ? `packages/${argv.scope}/src` : ''
}`;

execSync(cmd, { stdio: 'inherit' });
