import {
  removeCategory,
  removeAllChoices,
  limitInArrays,
  limitInArray,
  ensureNoExtraChoicesInAnswer,
  ensureNoExtraChoicesInAlternate,
  countInAnswer,
  countInChoices,
  countChosen,
  rearrangeChoices,
  verifyAllowMultiplePlacements,
  removeChoiceFromCategory,
  moveChoiceToCategory,
  moveChoiceToAlternate,
  stillSelectable,
  buildChoices,
  getBuiltCategories,
  getAllPossibleResponses,
  buildCategories,
  buildState,
} from './code/categorize';

export {
  removeCategory,
  removeAllChoices,
  limitInArrays,
  limitInArray,
  ensureNoExtraChoicesInAnswer,
  ensureNoExtraChoicesInAlternate,
  countInAnswer,
  countInChoices,
  countChosen,
  rearrangeChoices,
  verifyAllowMultiplePlacements,
  removeChoiceFromCategory,
  moveChoiceToCategory,
  moveChoiceToAlternate,
  stillSelectable,
  buildChoices,
  getBuiltCategories,
  getAllPossibleResponses,
  buildCategories,
  buildState,
};
