name: PIE Lib CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   # REQUIRED for lerna version
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: yarn
      - run: yarn install
      - run: scripts/release --build
      - run: scripts/release --test

  build-next:
    needs: test
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write   # REQUIRED for npm trusted publishing
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   # REQUIRED for lerna version
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: yarn
      - run: yarn install
      - run: scripts/release --build
      - run: scripts/release --release --next --loglevel verbose

  build-release:
    needs: test
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write   # REQUIRED for npm trusted publishing
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   # REQUIRED for lerna version
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: yarn
      - run: yarn install
      - run: scripts/release --build
      - run: scripts/release --release --loglevel verbose
